### ISSUE TITLE
is it compatible with redmine 3.2.x ?

### ISSUE THREAD

**Issue by msneet** [artemasmith/redmine_group_manager#6]
very usefull plugin
but is it compatible with actual versions?

**Comment by artemasmith** [comment]
Hi, i didn't try. You may make pull request, I'll check it and merge.
15 апр. 2016 г. 14:16 пользователь "msneet" <notifications@github.com>
написал:

**Comment by fathomssen** [comment]
Hi, until my pull request has been merged, you can use my forked version: https://github.com/fathomssen/groupmanager

Best regards
Frederick Thomssen

**Comment by w0www** [comment]
@fathomssen  have you a PR do? I think that its important that the official GIT page has the last changes

**Comment by w0www** [comment]
CLOSE THIS ISSUE PLEASE!
